apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
    app: trireme-graph
  name: trireme-graph
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: trireme-graph
    spec:
      containers:
        - image: aporeto/trireme-statistics:latest
          imagePullPolicy: Always
          name: trireme-graph
          env:
             - name: TRIREME_LOGLEVEL
               valueFrom:
                 configMapKeyRef:
                   key: trireme.log_level
                   name: trireme-config
                   optional: true
             - name: TRIREME_INFLUXURL
               valueFrom:
                 configMapKeyRef:
                   key: trireme.collector_endpoint
                   name: trireme-config
                   optional: true
             - name: TRIREME_INFLUXUSERNAME
               valueFrom:
                 configMapKeyRef:
                   key: trireme.collector_user
                   name: trireme-config
                   optional: true
             - name: TRIREME_INFLUXPASSWORD
               valueFrom:
                 configMapKeyRef:
                   key: trireme.collector_password
                   name: trireme-config
                   optional: true
             - name: TRIREME_INFLUXDBNAME
               valueFrom:
                 configMapKeyRef:
                   key: trireme.collector_db
                   name: trireme-config
                   optional: true
             - name: TRIREME_DBSKIPTLS
               valueFrom:
                 configMapKeyRef:
                   key: trireme.collector_insecure_skip_verify
                   name: trireme-config
                   optional: true
---
kind: Service
apiVersion: v1
metadata:
  name: graph
  namespace: kube-system
spec:
  selector:
    app: trireme-graph
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: graph-public
  namespace: kube-system
spec:
  selector:
    app: trireme-graph
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
