apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: trireme
  namespace: kube-system
data:
  trireme.log_level: trace
  trireme.auth_type: PKI
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: aporeto
  name: trireme
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: trireme
    spec:
      serviceAccountName: trireme-account
      hostNetwork: true
      hostPID: true
      containers:
        -  name: trireme
           image: aporeto/trireme-kubernetes:latest
           env:
             - name: TRIREME_LOGLEVEL
               valueFrom:
                 configMapKeyRef:
                   key: trireme.log_level
                   name: trireme
                   optional: true
             - name: TRIREME_AUTHTYPE
               valueFrom:
                 configMapKeyRef:
                   key: trireme.auth_type
                   name: trireme
             - name: TRIREME_KUBENODENAME
               valueFrom:
                 fieldRef:
                   fieldPath: spec.host
           securityContext:
             privileged: true
           volumeMounts:
             - mountPath: /var/run
               name: dockersock
               readOnly: false

      volumes:
        - name: dockersock
          hostPath:
            path: /var/run
