apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: aporeto
  name: trireme
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: trireme
    spec:
      serviceAccountName: trireme-account
      hostNetwork: true
      hostPID: true
      containers:
        -  name: trireme
           image: aporeto/trireme-kubernetes
           env:
             - name: TRIREME_AUTHTYPE
               value: PSK
             - name: TRIREME_LOGLEVEL
               value: debug
             - name: TRIREME_PSK
               valueFrom:
                 secretKeyRef:
                   name: trireme
                   key: triremepsk
             - name: TRIREME_KUBENODENAME
               valueFrom:
                 fieldRef:
                   fieldPath: spec.host
           securityContext:
             privileged: true
           volumeMounts:
             - mountPath: /var/run
               name: dockersock
               readOnly: false

      volumes:
        - name: dockersock
          hostPath:
            path: /var/run
