kind: ServiceAccount
apiVersion: v1
metadata:
  name: trireme-account
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: trireme-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: trireme-binding
subjects:
- kind: ServiceAccount
  name: trireme-account
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: trireme-role
  apiGroup: rbac.authorization.k8s.io
