kind: ServiceAccount
apiVersion: v1
metadata:
  name: trireme-csr-controller-account
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: trireme-cert-generator
rules:
- apiGroups:
  - "certmanager.k8s.io"
  resources:
  - "certificates"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: trireme-cert-generator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trireme-cert-generator
subjects:
- kind: ServiceAccount
  name: trireme-csr-controller-account
  namespace: kube-system