apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: aporeto
  name: trireme
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: trireme
    spec:
      serviceAccountName: trireme-enforcer-account
      hostNetwork: true
      hostPID: true
      containers:
        -  name: trireme
           image: aporeto/trireme-kubernetes:latest
           imagePullPolicy: Always
           env:
             - name: TRIREME_LOGLEVEL
               valueFrom:
                 configMapKeyRef:
                   key: trireme.log_level
                   name: trireme-config
                   optional: true
             - name: TRIREME_AUTHTYPE
               valueFrom:
                 configMapKeyRef:
                   key: trireme.auth_type
                   name: trireme-config
             - name: TRIREME_COLLECTORENDPOINT
               valueFrom:
                 configMapKeyRef:
                   key: trireme.collector_endpoint
                   name: trireme-config
             - name: TRIREME_COLLECTORUSER
               valueFrom:
                 configMapKeyRef:
                   key: trireme.collector_user
                   name: trireme-config
             - name: TRIREME_COLLECTORPASS
               valueFrom:
                 configMapKeyRef:
                   key: trireme.collector_password
                   name: trireme-config
             - name: TRIREME_COLLECTORDB
               valueFrom:
                 configMapKeyRef:
                   key: trireme.collector_db
                   name: trireme-config
             - name: TRIREME_COLLECTORINSECURESKIPVERIFY
               valueFrom:
                 configMapKeyRef:
                   key: trireme.collector_insecure_skip_verify
                   name: trireme-config
             - name: TRIREME_PSK
               valueFrom:
                 secretKeyRef:
                   name: trireme
                   key: triremepsk
                   optional: true
             - name: TRIREME_KUBENODENAME
               valueFrom:
                 fieldRef:
                   fieldPath: spec.host
           securityContext:
             privileged: true
           volumeMounts:
             - mountPath: /var/run
               name: dockersock
               readOnly: false

      volumes:
        - name: dockersock
          hostPath:
            path: /var/run
